version: "3"
services:
  hub:
    image: selenium/hub:3.14
    container_name: hub
    ports:
     - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14      
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '1gb'   
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  samsung_galaxy:
   image: butomo1989/docker-android-x86-8.1
   privileged: true
   depends_on:
     - hub
   ports:
     - "6080:6080"
   environment:
     - DEVICE=Samsung Galaxy S6
     - CONNECT_TO_GRID=True
     - APPIUM=true
     - SELENIUM_HOST=hub
     - MOBILE_WEB_TEST=False
     - AUTO_RECORD=True
  search-module:
    image: kittu1023/selenium-docker
    depends_on:
      - chrome
      - firefox
      - samsung_galaxy
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=search-module.xml
    volumes:
      - ./output/search-result:/usr/share/udemy/test-output
  book-flight-module:
    image: kittu1023/selenium-docker
    depends_on:
      - chrome
      - firefox
      - samsung_galaxy
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=book-flight-module.xml
    volumes:
      - ./output/search-result:/usr/share/udemy/test-output
    sample-app-module:
    image: kittu1023/selenium-docker
    depends_on:
      - chrome
      - firefox
      - samsung_galaxy
    environment:
      - HUB_HOST=hub
      - BROWSER=android
      - MODULE=sample-apptest.xml
    volumes:
      - ./output/book-result:/usr/share/udemy/test-output